version: '3'

volumes:
  app:
    driver: 'lebokus/bindfs:latest'
    driver_opts:
      sourcePath: '${PWD}/${DATA_SOURCE_PATH}'
      map: '${UID}/33:@${UID}/@33'

services:
  nextcloud-app:
    image: 'nextcloud:fpm'
    container_name: nextcloud-app
    volumes:
      - app:/var/www/html
    restart: unless-stopped
    networks:
      - proxy-net
  nextcloud-web:
    build:
      context: .
      dockerfile: nextcloud.dockerfile
    container_name: nextcloud-web
    depends_on:
      - nextcloud-app
    volumes:
      - app:/var/www/html
    restart: unless-stopped
    environment:
      - 'VIRTUAL_HOST=${NEXTCLOUD_HOST}'
      - 'VIRTUAL_NETWORK=${PROXY_HOST}'
      - 'VIRTUAL_PORT=80'
      - 'LETSENCRYPT_HOST=${NEXTCLOUD_HOST}'
      - 'LETSENCRYPT_EMAIL=${LE_EMAIL}'
    ports:
      - '8001:80'
    networks:
      - proxy-net

networks:
  proxy-net:
    name: home-server_proxy-tier
    external: true
