version: '3.9'

volumes:
  nc-app:
  nc-data:
    driver: 'local'
    driver_opts:
      type: none
      device: '${PWD}/${DATA_SOURCE_PATH}'
      o: bind

services:
  cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-cron
    restart: unless-stopped
    volumes:
      - nc-app:/var/www/html
    entrypoint: /cron.sh
    networks:
      - proxy-net

  nextcloud-app:
    image: 'nextcloud:fpm'
    container_name: nextcloud-app
    volumes:
      - nc-app:/var/www/html
      - nc-data:/var/www/html/data
    restart: unless-stopped
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_HOST}
      - REDIS_HOST=redis
    networks:
      - proxy-net

  nextcloud-web:
    build:
      context: .
      dockerfile: nextcloud-web.dockerfile
    container_name: nextcloud-web
    depends_on:
      - nextcloud-app
    volumes:
      - nc-app:/var/www/html
      - nc-data:/var/www/html/data
    restart: unless-stopped
    environment:
      - 'VIRTUAL_HOST=${NEXTCLOUD_HOST}'
      - 'VIRTUAL_NETWORK=${PROXY_HOST}'
      - 'VIRTUAL_PORT=80'
      - 'LETSENCRYPT_HOST=${NEXTCLOUD_HOST}'
      - 'LETSENCRYPT_EMAIL=${LE_EMAIL}'
    ports:
      - '8001:80'
    networks:
      - proxy-net

networks:
  proxy-net:
    name: home-server_proxy-tier
    external: true
